apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-metrics
  labels:
    app: test-app-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-metrics
  template:
    metadata:
      labels:
        app: test-app-metrics
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args: ["-nginx.scrape-uri", "http://localhost:80/stub_status"]
        ports:
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-metrics
spec:
  selector:
    app: test-app-metrics
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  type: NodePort
